# Generated by Django 5.0.1 on 2025-12-01 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('local', 'Local Payment'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('authorize_net', 'Authorize.Net'), ('2checkout', '2Checkout'), ('payu_latam', 'PayU Latam'), ('payson', 'Payson'), ('mollie', 'Mollie'), ('coupon', 'Coupon (100% discount)'), ('woocommerce', 'WooCommerce')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('details', models.JSONField(blank=True, default=dict, help_text='Payment details (items, customer info, etc.)')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'type'], name='payments_pa_status_a6803a_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
