# Generated by Django 5.0.1 on 2025-12-01 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Coupon code (case-insensitive)', max_length=50, unique=True)),
                ('discount', models.IntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount deduction', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.IntegerField(default=1, help_text='Maximum number of times coupon can be used', validators=[django.core.validators.MinValueValidator(1)])),
                ('used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(blank=True, help_text='Coupon validity start date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Coupon validity end date', null=True)),
                ('services', models.ManyToManyField(blank=True, help_text='Services this coupon applies to (empty = all services)', related_name='coupons', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx')],
            },
        ),
    ]
