-- VALClean schema: all tables for Supabase (PostgreSQL)
-- Generated from Django migrations in dependency order.
-- Run this in Supabase Dashboard -> SQL Editor if you cannot run Django migrate.

-- contenttypes.0001_initial
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- contenttypes.0002_remove_content_type_name
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;
COMMIT;

-- auth.0001_initial
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
COMMIT;

-- auth.0002_alter_permission_name_max_length
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- auth.0003_alter_user_email_max_length
BEGIN;
--
-- Alter field email on user
--
-- (no-op)
COMMIT;

-- auth.0004_alter_user_username_opts
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- auth.0005_alter_user_last_login_null
BEGIN;
--
-- Alter field last_login on user
--
-- (no-op)
COMMIT;

-- auth.0007_alter_validators_add_error_messages
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- auth.0008_alter_user_username_max_length
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- auth.0009_alter_user_last_name_max_length
BEGIN;
--
-- Alter field last_name on user
--
-- (no-op)
COMMIT;

-- auth.0010_alter_group_name_max_length
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- auth.0011_update_proxy_permissions
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- auth.0012_alter_user_first_name_max_length
BEGIN;
--
-- Alter field first_name on user
--
-- (no-op)
COMMIT;

-- sessions.0001_initial
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;

-- admin.0001_initial
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;

-- admin.0002_logentry_remove_auto_add
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- admin.0003_logentry_add_action_flag_choices
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- services.0001_initial
BEGIN;
--
-- Create model Category
--
CREATE TABLE "services_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE, "description" text NULL, "image" varchar(100) NULL, "position" integer NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model Service
--
CREATE TABLE "services_service" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(200) NOT NULL, "slug" varchar(200) NOT NULL, "description" text NULL, "duration" integer NOT NULL, "price" numeric(10, 2) NOT NULL, "currency" varchar(3) NOT NULL, "image" varchar(100) NULL, "color" varchar(7) NOT NULL, "capacity" integer NOT NULL, "padding_time" integer NOT NULL, "position" integer NOT NULL, "is_active" boolean NOT NULL, "category_id" bigint NOT NULL);
CREATE INDEX "services_category_name_99124e6b_like" ON "services_category" ("name" varchar_pattern_ops);
CREATE INDEX "services_category_slug_82e59540_like" ON "services_category" ("slug" varchar_pattern_ops);
ALTER TABLE "services_service" ADD CONSTRAINT "services_service_category_id_e15f8b7e_fk_services_category_id" FOREIGN KEY ("category_id") REFERENCES "services_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "services_service_slug_a56f96e2" ON "services_service" ("slug");
CREATE INDEX "services_service_slug_a56f96e2_like" ON "services_service" ("slug" varchar_pattern_ops);
CREATE INDEX "services_service_category_id_e15f8b7e" ON "services_service" ("category_id");
CREATE INDEX "services_se_categor_b50c86_idx" ON "services_service" ("category_id", "is_active");
CREATE INDEX "services_se_slug_4657d0_idx" ON "services_service" ("slug");
COMMIT;

-- customers.0001_initial
BEGIN;
--
-- Create model Customer
--
CREATE TABLE "customers_customer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(200) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(20) NULL, "address_line1" varchar(255) NULL, "address_line2" varchar(255) NULL, "city" varchar(100) NULL, "postcode" varchar(20) NULL, "country" varchar(100) NOT NULL, "address_validated" boolean NOT NULL, "notes" text NULL, "tags" jsonb NOT NULL, "user_id" bigint NULL);
--
-- Create model Address
--
CREATE TABLE "customers_address" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "type" varchar(20) NOT NULL, "address_line1" varchar(255) NOT NULL, "address_line2" varchar(255) NULL, "city" varchar(100) NOT NULL, "postcode" varchar(20) NOT NULL, "country" varchar(100) NOT NULL, "is_default" boolean NOT NULL, "address_validated" boolean NOT NULL, "customer_id" bigint NOT NULL);
--
-- Create index customers_c_email_4fdeb3_idx on field(s) email of model customer
--
CREATE INDEX "customers_c_email_4fdeb3_idx" ON "customers_customer" ("email");
--
-- Create index customers_c_postcod_729241_idx on field(s) postcode of model customer
--
CREATE INDEX "customers_c_postcod_729241_idx" ON "customers_customer" ("postcode");
--
-- Create index customers_c_user_id_c1d57c_idx on field(s) user of model customer
--
CREATE INDEX "customers_c_user_id_c1d57c_idx" ON "customers_customer" ("user_id");
ALTER TABLE "customers_customer" ADD CONSTRAINT "customers_customer_user_id_a9568d6c_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "customers_customer_user_id_a9568d6c" ON "customers_customer" ("user_id");
ALTER TABLE "customers_address" ADD CONSTRAINT "customers_address_customer_id_f042422e_fk_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "customers_address_customer_id_f042422e" ON "customers_address" ("customer_id");
COMMIT;

-- accounts.0001_initial
BEGIN;
--
-- Create model User
--
CREATE TABLE "accounts_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "role" varchar(20) NOT NULL, "is_verified" boolean NOT NULL, "username" varchar(150) NULL UNIQUE);
CREATE TABLE "accounts_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "accounts_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Manager
--
CREATE TABLE "accounts_manager" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "permissions" jsonb NOT NULL, "can_manage_all" boolean NOT NULL, "can_manage_customers" boolean NOT NULL, "can_manage_staff" boolean NOT NULL, "can_manage_appointments" boolean NOT NULL, "can_view_reports" boolean NOT NULL, "managed_locations" jsonb NOT NULL, "is_active" boolean NOT NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Profile
--
CREATE TABLE "accounts_profile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "phone" varchar(20) NULL, "avatar" varchar(100) NULL, "timezone" varchar(50) NOT NULL, "preferences" jsonb NOT NULL, "calendar_sync_enabled" boolean NOT NULL, "calendar_provider" varchar(20) NOT NULL, "calendar_access_token" text NULL, "calendar_refresh_token" text NULL, "calendar_calendar_id" varchar(255) NULL, "calendar_sync_settings" jsonb NOT NULL, "user_id" bigint NOT NULL UNIQUE);
CREATE INDEX "accounts_user_email_b2644a56_like" ON "accounts_user" ("email" varchar_pattern_ops);
CREATE INDEX "accounts_user_username_6088629e_like" ON "accounts_user" ("username" varchar_pattern_ops);
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_group_id_59c0b32f_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_52b62117_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_group_id_bd11a704_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_user_id_e4f0a161_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_permission_id_113bb443_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
ALTER TABLE "accounts_manager" ADD CONSTRAINT "accounts_manager_user_id_f3ea9b9b_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_profile" ADD CONSTRAINT "accounts_profile_user_id_49a85d32_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;

-- staff.0001_initial
BEGIN;
--
-- Create model Staff
--
CREATE TABLE "staff_staff" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(200) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(20) NULL, "photo" varchar(100) NULL, "bio" text NULL, "is_active" boolean NOT NULL, "user_id" bigint NULL);
--
-- Create model StaffService
--
CREATE TABLE "staff_staffservice" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "price_override" numeric(10, 2) NULL, "duration_override" integer NULL, "is_active" boolean NOT NULL, "service_id" bigint NOT NULL, "staff_id" bigint NOT NULL);
--
-- Add field services to staff
--
-- (no-op)
--
-- Create model StaffArea
--
CREATE TABLE "staff_staffarea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "postcode" varchar(20) NOT NULL, "radius_km" numeric(5, 2) NOT NULL, "is_active" boolean NOT NULL, "staff_id" bigint NOT NULL);
--
-- Create model StaffSchedule
--
CREATE TABLE "staff_staffschedule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "day_of_week" integer NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "breaks" jsonb NOT NULL, "is_active" boolean NOT NULL, "staff_id" bigint NOT NULL);
--
-- Create index staff_staff_is_acti_5c62d9_idx on field(s) is_active, email of model staff
--
CREATE INDEX "staff_staff_is_acti_5c62d9_idx" ON "staff_staff" ("is_active", "email");
ALTER TABLE "staff_staff" ADD CONSTRAINT "staff_staff_user_id_abd8ba40_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "staff_staff_user_id_abd8ba40" ON "staff_staff" ("user_id");
ALTER TABLE "staff_staffservice" ADD CONSTRAINT "staff_staffservice_staff_id_service_id_ff58722c_uniq" UNIQUE ("staff_id", "service_id");
ALTER TABLE "staff_staffservice" ADD CONSTRAINT "staff_staffservice_service_id_01945e4d_fk_services_service_id" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "staff_staffservice" ADD CONSTRAINT "staff_staffservice_staff_id_7fd8d67b_fk_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff_staff" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "staff_staffservice_service_id_01945e4d" ON "staff_staffservice" ("service_id");
CREATE INDEX "staff_staffservice_staff_id_7fd8d67b" ON "staff_staffservice" ("staff_id");
ALTER TABLE "staff_staffarea" ADD CONSTRAINT "staff_staffarea_staff_id_b262595a_fk_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff_staff" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "staff_staffarea_staff_id_b262595a" ON "staff_staffarea" ("staff_id");
CREATE INDEX "staff_staff_postcod_17cd79_idx" ON "staff_staffarea" ("postcode", "is_active");
CREATE INDEX "staff_staff_staff_i_a895cf_idx" ON "staff_staffarea" ("staff_id", "is_active");
ALTER TABLE "staff_staffschedule" ADD CONSTRAINT "staff_staffschedule_staff_id_day_of_week_141ee61e_uniq" UNIQUE ("staff_id", "day_of_week");
ALTER TABLE "staff_staffschedule" ADD CONSTRAINT "staff_staffschedule_staff_id_3aee1a6c_fk_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff_staff" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "staff_staffschedule_staff_id_3aee1a6c" ON "staff_staffschedule" ("staff_id");
COMMIT;

-- appointments.0001_initial
BEGIN;
--
-- Create model Appointment
--
CREATE TABLE "appointments_appointment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "start_time" timestamp with time zone NOT NULL, "end_time" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "appointment_type" varchar(20) NOT NULL, "calendar_event_id" jsonb NOT NULL, "calendar_synced_to" jsonb NOT NULL, "internal_notes" text NULL, "location_notes" text NULL);
--
-- Create model CustomerAppointment
--
CREATE TABLE "appointments_customerappointment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "number_of_persons" integer NOT NULL, "extras" jsonb NOT NULL, "custom_fields" jsonb NOT NULL, "total_price" numeric(10, 2) NOT NULL, "deposit_paid" numeric(10, 2) NOT NULL, "payment_status" varchar(20) NOT NULL, "cancellation_token" varchar(100) NULL UNIQUE, "cancellation_policy_hours" integer NOT NULL, "cancellation_deadline" timestamp with time zone NULL, "can_cancel" boolean NOT NULL, "can_reschedule" boolean NOT NULL);
CREATE INDEX "appointments_customerapp_cancellation_token_ffe83d25_like" ON "appointments_customerappointment" ("cancellation_token" varchar_pattern_ops);
COMMIT;

-- orders.0001_initial
BEGIN;
--
-- Create model Order
--
CREATE TABLE "orders_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "guest_email" varchar(254) NULL, "guest_name" varchar(200) NULL, "guest_phone" varchar(20) NULL, "order_number" varchar(50) NOT NULL UNIQUE, "tracking_token" varchar(100) NOT NULL UNIQUE, "is_guest_order" boolean NOT NULL, "account_linked_at" timestamp with time zone NULL, "status" varchar(20) NOT NULL, "total_price" numeric(10, 2) NOT NULL, "deposit_paid" numeric(10, 2) NOT NULL, "payment_status" varchar(20) NOT NULL, "scheduled_date" date NOT NULL, "scheduled_time" time NULL, "cancellation_policy_hours" integer NOT NULL, "can_cancel" boolean NOT NULL, "can_reschedule" boolean NOT NULL, "cancellation_deadline" timestamp with time zone NULL, "address_line1" varchar(255) NOT NULL, "address_line2" varchar(255) NULL, "city" varchar(100) NOT NULL, "postcode" varchar(20) NOT NULL, "country" varchar(100) NOT NULL, "notes" text NULL, "customer_id" bigint NULL);
--
-- Create model OrderItem
--
CREATE TABLE "orders_orderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10, 2) NOT NULL, "total_price" numeric(10, 2) NOT NULL, "status" varchar(20) NOT NULL, "notes" text NULL, "appointment_id" bigint NULL, "order_id" bigint NOT NULL, "service_id" bigint NOT NULL, "staff_id" bigint NULL);
--
-- Create index orders_orde_order_n_f3ada5_idx on field(s) order_number of model order
--
CREATE INDEX "orders_orde_order_n_f3ada5_idx" ON "orders_order" ("order_number");
--
-- Create index orders_orde_trackin_fb511c_idx on field(s) tracking_token of model order
--
CREATE INDEX "orders_orde_trackin_fb511c_idx" ON "orders_order" ("tracking_token");
--
-- Create index orders_orde_custome_c9b64a_idx on field(s) customer, status of model order
--
CREATE INDEX "orders_orde_custome_c9b64a_idx" ON "orders_order" ("customer_id", "status");
--
-- Create index orders_orde_is_gues_8217f9_idx on field(s) is_guest_order, guest_email of model order
--
CREATE INDEX "orders_orde_is_gues_8217f9_idx" ON "orders_order" ("is_guest_order", "guest_email");
--
-- Create index orders_orde_status_03ad6e_idx on field(s) status, scheduled_date of model order
--
CREATE INDEX "orders_orde_status_03ad6e_idx" ON "orders_order" ("status", "scheduled_date");
--
-- Create index orders_orde_postcod_372e67_idx on field(s) postcode of model order
--
CREATE INDEX "orders_orde_postcod_372e67_idx" ON "orders_order" ("postcode");
--
-- Create index orders_orde_order_i_3360fc_idx on field(s) order, status of model orderitem
--
CREATE INDEX "orders_orde_order_i_3360fc_idx" ON "orders_orderitem" ("order_id", "status");
--
-- Create index orders_orde_service_4e362f_idx on field(s) service of model orderitem
--
CREATE INDEX "orders_orde_service_4e362f_idx" ON "orders_orderitem" ("service_id");
--
-- Create index orders_orde_staff_i_6686ea_idx on field(s) staff of model orderitem
--
CREATE INDEX "orders_orde_staff_i_6686ea_idx" ON "orders_orderitem" ("staff_id");
ALTER TABLE "orders_order" ADD CONSTRAINT "orders_order_customer_id_0b76f6a4_fk_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_order_order_number_4e985f70_like" ON "orders_order" ("order_number" varchar_pattern_ops);
CREATE INDEX "orders_order_tracking_token_c0dd4d3d_like" ON "orders_order" ("tracking_token" varchar_pattern_ops);
CREATE INDEX "orders_order_customer_id_0b76f6a4" ON "orders_order" ("customer_id");
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_appointment_id_8fc0f4fa_fk_appointme" FOREIGN KEY ("appointment_id") REFERENCES "appointments_appointment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_order_id_fe61a34d_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_service_id_5cb17446_fk_services_service_id" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_staff_id_7fc9187c_fk_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff_staff" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_orderitem_appointment_id_8fc0f4fa" ON "orders_orderitem" ("appointment_id");
CREATE INDEX "orders_orderitem_order_id_fe61a34d" ON "orders_orderitem" ("order_id");
CREATE INDEX "orders_orderitem_service_id_5cb17446" ON "orders_orderitem" ("service_id");
CREATE INDEX "orders_orderitem_staff_id_7fc9187c" ON "orders_orderitem" ("staff_id");
COMMIT;

-- appointments.0002_initial
BEGIN;
--
-- Add field order to appointment
--
ALTER TABLE "appointments_appointment" ADD COLUMN "order_id" bigint NULL CONSTRAINT "appointments_appointment_order_id_669d6867_fk_orders_order_id" REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "appointments_appointment_order_id_669d6867_fk_orders_order_id" IMMEDIATE;
--
-- Add field service to appointment
--
ALTER TABLE "appointments_appointment" ADD COLUMN "service_id" bigint NOT NULL CONSTRAINT "appointments_appoint_service_id_945bc869_fk_services_" REFERENCES "services_service"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "appointments_appoint_service_id_945bc869_fk_services_" IMMEDIATE;
--
-- Add field staff to appointment
--
ALTER TABLE "appointments_appointment" ADD COLUMN "staff_id" bigint NOT NULL CONSTRAINT "appointments_appointment_staff_id_64350136_fk_staff_staff_id" REFERENCES "staff_staff"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "appointments_appointment_staff_id_64350136_fk_staff_staff_id" IMMEDIATE;
--
-- Add field subscription to appointment
--
ALTER TABLE "appointments_appointment" ADD COLUMN "subscription_id" bigint NULL CONSTRAINT "appointments_appoint_subscription_id_0f1eaa5e_fk_subscript" REFERENCES "subscriptions_subscription"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "appointments_appoint_subscription_id_0f1eaa5e_fk_subscript" IMMEDIATE;
--
-- Add field appointment to customerappointment
--
ALTER TABLE "appointments_customerappointment" ADD COLUMN "appointment_id" bigint NOT NULL UNIQUE CONSTRAINT "appointments_custome_appointment_id_ab140e3b_fk_appointme" REFERENCES "appointments_appointment"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "appointments_custome_appointment_id_ab140e3b_fk_appointme" IMMEDIATE;
--
-- Add field customer to customerappointment
--
ALTER TABLE "appointments_customerappointment" ADD COLUMN "customer_id" bigint NOT NULL CONSTRAINT "appointments_custome_customer_id_13ebe56a_fk_customers" REFERENCES "customers_customer"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "appointments_custome_customer_id_13ebe56a_fk_customers" IMMEDIATE;
--
-- Create index appointment_staff_i_7434a5_idx on field(s) staff, start_time of model appointment
--
CREATE INDEX "appointment_staff_i_7434a5_idx" ON "appointments_appointment" ("staff_id", "start_time");
--
-- Create index appointment_status_74937b_idx on field(s) status, start_time of model appointment
--
CREATE INDEX "appointment_status_74937b_idx" ON "appointments_appointment" ("status", "start_time");
--
-- Create index appointment_appoint_3d8254_idx on field(s) appointment_type of model appointment
--
CREATE INDEX "appointment_appoint_3d8254_idx" ON "appointments_appointment" ("appointment_type");
--
-- Create index appointment_subscri_de1689_idx on field(s) subscription of model appointment
--
CREATE INDEX "appointment_subscri_de1689_idx" ON "appointments_appointment" ("subscription_id");
--
-- Create index appointment_order_i_facef5_idx on field(s) order of model appointment
--
CREATE INDEX "appointment_order_i_facef5_idx" ON "appointments_appointment" ("order_id");
--
-- Create index appointment_custome_413569_idx on field(s) customer of model customerappointment
--
CREATE INDEX "appointment_custome_413569_idx" ON "appointments_customerappointment" ("customer_id");
--
-- Create index appointment_cancell_ccec98_idx on field(s) cancellation_token of model customerappointment
--
CREATE INDEX "appointment_cancell_ccec98_idx" ON "appointments_customerappointment" ("cancellation_token");
--
-- Create index appointment_can_can_14af65_idx on field(s) can_cancel, can_reschedule of model customerappointment
--
CREATE INDEX "appointment_can_can_14af65_idx" ON "appointments_customerappointment" ("can_cancel", "can_reschedule");
CREATE INDEX "appointments_appointment_order_id_669d6867" ON "appointments_appointment" ("order_id");
CREATE INDEX "appointments_appointment_service_id_945bc869" ON "appointments_appointment" ("service_id");
CREATE INDEX "appointments_appointment_staff_id_64350136" ON "appointments_appointment" ("staff_id");
CREATE INDEX "appointments_appointment_subscription_id_0f1eaa5e" ON "appointments_appointment" ("subscription_id");
CREATE INDEX "appointments_customerappointment_customer_id_13ebe56a" ON "appointments_customerappointment" ("customer_id");
COMMIT;

-- subscriptions.0001_initial
BEGIN;
--
-- Create model Subscription
--
CREATE TABLE "subscriptions_subscription" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "guest_email" varchar(254) NULL, "guest_name" varchar(200) NULL, "guest_phone" varchar(20) NULL, "subscription_number" varchar(50) NOT NULL UNIQUE, "tracking_token" varchar(100) NOT NULL UNIQUE, "is_guest_subscription" boolean NOT NULL, "account_linked_at" timestamp with time zone NULL, "frequency" varchar(20) NOT NULL, "duration_months" integer NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "next_appointment_date" date NULL, "status" varchar(20) NOT NULL, "total_appointments" integer NOT NULL, "completed_appointments" integer NOT NULL, "price_per_appointment" numeric(10, 2) NOT NULL, "total_price" numeric(10, 2) NOT NULL, "payment_status" varchar(20) NOT NULL, "cancellation_policy_hours" integer NOT NULL, "address_line1" varchar(255) NULL, "address_line2" varchar(255) NULL, "city" varchar(100) NULL, "postcode" varchar(20) NULL, "country" varchar(100) NULL, "customer_id" bigint NULL, "service_id" bigint NOT NULL, "staff_id" bigint NULL);
--
-- Create model SubscriptionAppointment
--
CREATE TABLE "subscriptions_subscriptionappointment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "sequence_number" integer NOT NULL, "scheduled_date" date NOT NULL, "status" varchar(20) NOT NULL, "can_cancel" boolean NOT NULL, "cancellation_deadline" timestamp with time zone NULL, "appointment_id" bigint NOT NULL, "subscription_id" bigint NOT NULL);
--
-- Create index subscriptio_subscri_c33376_idx on field(s) subscription_number of model subscription
--
CREATE INDEX "subscriptio_subscri_c33376_idx" ON "subscriptions_subscription" ("subscription_number");
--
-- Create index subscriptio_trackin_ad3212_idx on field(s) tracking_token of model subscription
--
CREATE INDEX "subscriptio_trackin_ad3212_idx" ON "subscriptions_subscription" ("tracking_token");
--
-- Create index subscriptio_custome_cea13a_idx on field(s) customer, status of model subscription
--
CREATE INDEX "subscriptio_custome_cea13a_idx" ON "subscriptions_subscription" ("customer_id", "status");
--
-- Create index subscriptio_is_gues_04a947_idx on field(s) is_guest_subscription, guest_email of model subscription
--
CREATE INDEX "subscriptio_is_gues_04a947_idx" ON "subscriptions_subscription" ("is_guest_subscription", "guest_email");
--
-- Create index subscriptio_status_a8dc67_idx on field(s) status, next_appointment_date of model subscription
--
CREATE INDEX "subscriptio_status_a8dc67_idx" ON "subscriptions_subscription" ("status", "next_appointment_date");
--
-- Alter unique_together for subscriptionappointment (1 constraint(s))
--
ALTER TABLE "subscriptions_subscriptionappointment" ADD CONSTRAINT "subscriptions_subscripti_subscription_id_appointm_438adbae_uniq" UNIQUE ("subscription_id", "appointment_id");
ALTER TABLE "subscriptions_subscription" ADD CONSTRAINT "subscriptions_subscr_customer_id_a993be05_fk_customers" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions_subscription" ADD CONSTRAINT "subscriptions_subscr_service_id_bbd8c424_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions_subscription" ADD CONSTRAINT "subscriptions_subscription_staff_id_2f587fc1_fk_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff_staff" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "subscriptions_subscription_subscription_number_d88ebde5_like" ON "subscriptions_subscription" ("subscription_number" varchar_pattern_ops);
CREATE INDEX "subscriptions_subscription_tracking_token_717520de_like" ON "subscriptions_subscription" ("tracking_token" varchar_pattern_ops);
CREATE INDEX "subscriptions_subscription_customer_id_a993be05" ON "subscriptions_subscription" ("customer_id");
CREATE INDEX "subscriptions_subscription_service_id_bbd8c424" ON "subscriptions_subscription" ("service_id");
CREATE INDEX "subscriptions_subscription_staff_id_2f587fc1" ON "subscriptions_subscription" ("staff_id");
ALTER TABLE "subscriptions_subscriptionappointment" ADD CONSTRAINT "subscriptions_subscr_appointment_id_7c52147c_fk_appointme" FOREIGN KEY ("appointment_id") REFERENCES "appointments_appointment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions_subscriptionappointment" ADD CONSTRAINT "subscriptions_subscr_subscription_id_a3a20a07_fk_subscript" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions_subscription" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "subscriptions_subscriptionappointment_appointment_id_7c52147c" ON "subscriptions_subscriptionappointment" ("appointment_id");
CREATE INDEX "subscriptions_subscriptionappointment_subscription_id_a3a20a07" ON "subscriptions_subscriptionappointment" ("subscription_id");
COMMIT;

-- orders.0002_changerequest
BEGIN;
--
-- Create model ChangeRequest
--
CREATE TABLE "orders_changerequest" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "requested_date" date NOT NULL, "requested_time" time NULL, "reason" text NULL, "status" varchar(20) NOT NULL, "reviewed_at" timestamp with time zone NULL, "review_notes" text NULL, "order_id" bigint NOT NULL, "reviewed_by_id" bigint NULL);
ALTER TABLE "orders_changerequest" ADD CONSTRAINT "orders_changerequest_order_id_dc7649a7_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_changerequest" ADD CONSTRAINT "orders_changerequest_reviewed_by_id_e25fa953_fk_accounts_" FOREIGN KEY ("reviewed_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_changerequest_order_id_dc7649a7" ON "orders_changerequest" ("order_id");
CREATE INDEX "orders_changerequest_reviewed_by_id_e25fa953" ON "orders_changerequest" ("reviewed_by_id");
CREATE INDEX "orders_chan_order_i_06da21_idx" ON "orders_changerequest" ("order_id", "status");
COMMIT;

-- accounts.0002_manager_managed_customers_manager_managed_staff
BEGIN;
--
-- Add field managed_customers to manager
--
CREATE TABLE "accounts_manager_managed_customers" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "manager_id" bigint NOT NULL, "customer_id" bigint NOT NULL);
--
-- Add field managed_staff to manager
--
CREATE TABLE "accounts_manager_managed_staff" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "manager_id" bigint NOT NULL, "staff_id" bigint NOT NULL);
ALTER TABLE "accounts_manager_managed_customers" ADD CONSTRAINT "accounts_manager_managed_manager_id_customer_id_01e671de_uniq" UNIQUE ("manager_id", "customer_id");
ALTER TABLE "accounts_manager_managed_customers" ADD CONSTRAINT "accounts_manager_man_manager_id_9d7217c9_fk_accounts_" FOREIGN KEY ("manager_id") REFERENCES "accounts_manager" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_manager_managed_customers" ADD CONSTRAINT "accounts_manager_man_customer_id_75be6cea_fk_customers" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_manager_managed_customers_manager_id_9d7217c9" ON "accounts_manager_managed_customers" ("manager_id");
CREATE INDEX "accounts_manager_managed_customers_customer_id_75be6cea" ON "accounts_manager_managed_customers" ("customer_id");
ALTER TABLE "accounts_manager_managed_staff" ADD CONSTRAINT "accounts_manager_managed_manager_id_staff_id_361aef03_uniq" UNIQUE ("manager_id", "staff_id");
ALTER TABLE "accounts_manager_managed_staff" ADD CONSTRAINT "accounts_manager_man_manager_id_fa353d47_fk_accounts_" FOREIGN KEY ("manager_id") REFERENCES "accounts_manager" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_manager_managed_staff" ADD CONSTRAINT "accounts_manager_man_staff_id_5dc9d832_fk_staff_sta" FOREIGN KEY ("staff_id") REFERENCES "staff_staff" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_manager_managed_staff_manager_id_fa353d47" ON "accounts_manager_managed_staff" ("manager_id");
CREATE INDEX "accounts_manager_managed_staff_staff_id_5dc9d832" ON "accounts_manager_managed_staff" ("staff_id");
COMMIT;

-- accounts.0003_alter_manager_is_active_and_more
BEGIN;
--
-- Alter field is_active on manager
--
-- (no-op)
--
-- Alter field calendar_access_token on profile
--
-- (no-op)
--
-- Alter field calendar_calendar_id on profile
--
-- (no-op)
--
-- Alter field calendar_provider on profile
--
-- (no-op)
--
-- Alter field calendar_refresh_token on profile
--
-- (no-op)
--
-- Alter field calendar_sync_settings on profile
--
-- (no-op)
--
-- Create model Invitation
--
CREATE TABLE "accounts_invitation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL, "role" varchar(20) NOT NULL, "token" varchar(64) NOT NULL UNIQUE, "expires_at" timestamp with time zone NOT NULL, "used_at" timestamp with time zone NULL, "is_active" boolean NOT NULL, "invited_by_id" bigint NULL);
ALTER TABLE "accounts_invitation" ADD CONSTRAINT "accounts_invitation_invited_by_id_94a21efc_fk_accounts_user_id" FOREIGN KEY ("invited_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_invitation_token_b1be4c2b_like" ON "accounts_invitation" ("token" varchar_pattern_ops);
CREATE INDEX "accounts_invitation_invited_by_id_94a21efc" ON "accounts_invitation" ("invited_by_id");
CREATE INDEX "accounts_in_token_eb512a_idx" ON "accounts_invitation" ("token", "is_active");
CREATE INDEX "accounts_in_email_af4583_idx" ON "accounts_invitation" ("email", "role");
COMMIT;

-- staff.0002_convert_radius_to_miles
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Rename field radius_km on staffarea to radius_miles
--
ALTER TABLE "staff_staffarea" RENAME COLUMN "radius_km" TO "radius_miles";
--
-- Alter field radius_miles on staffarea
--
-- (no-op)
COMMIT;

-- coupons.0001_initial
BEGIN;
--
-- Create model Coupon
--
CREATE TABLE "coupons_coupon" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "code" varchar(50) NOT NULL UNIQUE, "name" varchar(200) NOT NULL, "discount_type" varchar(20) NOT NULL, "discount_value" numeric(10, 2) NOT NULL, "max_uses" integer NULL, "max_uses_per_customer" integer NULL, "used_count" integer NOT NULL, "valid_from" timestamp with time zone NOT NULL, "valid_until" timestamp with time zone NULL, "minimum_order_amount" numeric(10, 2) NOT NULL, "status" varchar(20) NOT NULL, "description" text NULL);
CREATE TABLE "coupons_coupon_applicable_services" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "coupon_id" bigint NOT NULL, "service_id" bigint NOT NULL);
CREATE TABLE "coupons_coupon_excluded_services" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "coupon_id" bigint NOT NULL, "service_id" bigint NOT NULL);
--
-- Create model CouponUsage
--
CREATE TABLE "coupons_couponusage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "guest_email" varchar(254) NULL, "discount_amount" numeric(10, 2) NOT NULL, "order_amount" numeric(10, 2) NOT NULL, "final_amount" numeric(10, 2) NOT NULL, "appointment_id" bigint NULL, "coupon_id" bigint NOT NULL, "customer_id" bigint NULL, "order_id" bigint NULL, "subscription_id" bigint NULL);
--
-- Create index coupons_cou_code_3bf721_idx on field(s) code of model coupon
--
CREATE INDEX "coupons_cou_code_3bf721_idx" ON "coupons_coupon" ("code");
--
-- Create index coupons_cou_status_a34176_idx on field(s) status, valid_from, valid_until of model coupon
--
CREATE INDEX "coupons_cou_status_a34176_idx" ON "coupons_coupon" ("status", "valid_from", "valid_until");
--
-- Create index coupons_cou_coupon__46300b_idx on field(s) coupon, customer of model couponusage
--
CREATE INDEX "coupons_cou_coupon__46300b_idx" ON "coupons_couponusage" ("coupon_id", "customer_id");
--
-- Create index coupons_cou_order_i_961167_idx on field(s) order of model couponusage
--
CREATE INDEX "coupons_cou_order_i_961167_idx" ON "coupons_couponusage" ("order_id");
--
-- Create index coupons_cou_subscri_aaaa86_idx on field(s) subscription of model couponusage
--
CREATE INDEX "coupons_cou_subscri_aaaa86_idx" ON "coupons_couponusage" ("subscription_id");
CREATE INDEX "coupons_coupon_code_40174643_like" ON "coupons_coupon" ("code" varchar_pattern_ops);
ALTER TABLE "coupons_coupon_applicable_services" ADD CONSTRAINT "coupons_coupon_applicabl_coupon_id_service_id_39959b9d_uniq" UNIQUE ("coupon_id", "service_id");
ALTER TABLE "coupons_coupon_applicable_services" ADD CONSTRAINT "coupons_coupon_appli_coupon_id_b1ed4c01_fk_coupons_c" FOREIGN KEY ("coupon_id") REFERENCES "coupons_coupon" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "coupons_coupon_applicable_services" ADD CONSTRAINT "coupons_coupon_appli_service_id_f1413327_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "coupons_coupon_applicable_services_coupon_id_b1ed4c01" ON "coupons_coupon_applicable_services" ("coupon_id");
CREATE INDEX "coupons_coupon_applicable_services_service_id_f1413327" ON "coupons_coupon_applicable_services" ("service_id");
ALTER TABLE "coupons_coupon_excluded_services" ADD CONSTRAINT "coupons_coupon_excluded__coupon_id_service_id_d1992d00_uniq" UNIQUE ("coupon_id", "service_id");
ALTER TABLE "coupons_coupon_excluded_services" ADD CONSTRAINT "coupons_coupon_exclu_coupon_id_cffee224_fk_coupons_c" FOREIGN KEY ("coupon_id") REFERENCES "coupons_coupon" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "coupons_coupon_excluded_services" ADD CONSTRAINT "coupons_coupon_exclu_service_id_711e0497_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "coupons_coupon_excluded_services_coupon_id_cffee224" ON "coupons_coupon_excluded_services" ("coupon_id");
CREATE INDEX "coupons_coupon_excluded_services_service_id_711e0497" ON "coupons_coupon_excluded_services" ("service_id");
ALTER TABLE "coupons_couponusage" ADD CONSTRAINT "coupons_couponusage_appointment_id_af021e86_fk_appointme" FOREIGN KEY ("appointment_id") REFERENCES "appointments_appointment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "coupons_couponusage" ADD CONSTRAINT "coupons_couponusage_coupon_id_b648d42e_fk_coupons_coupon_id" FOREIGN KEY ("coupon_id") REFERENCES "coupons_coupon" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "coupons_couponusage" ADD CONSTRAINT "coupons_couponusage_customer_id_62c5414b_fk_customers" FOREIGN KEY ("customer_id") REFERENCES "customers_customer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "coupons_couponusage" ADD CONSTRAINT "coupons_couponusage_order_id_9eb51d6d_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "coupons_couponusage" ADD CONSTRAINT "coupons_couponusage_subscription_id_070a064a_fk_subscript" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions_subscription" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "coupons_couponusage_appointment_id_af021e86" ON "coupons_couponusage" ("appointment_id");
CREATE INDEX "coupons_couponusage_coupon_id_b648d42e" ON "coupons_couponusage" ("coupon_id");
CREATE INDEX "coupons_couponusage_customer_id_62c5414b" ON "coupons_couponusage" ("customer_id");
CREATE INDEX "coupons_couponusage_order_id_9eb51d6d" ON "coupons_couponusage" ("order_id");
CREATE INDEX "coupons_couponusage_subscription_id_070a064a" ON "coupons_couponusage" ("subscription_id");
COMMIT;

