# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(help_text='Appointment start date and time')),
                ('end_time', models.DateTimeField(help_text='Appointment end date and time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', help_text='Appointment status', max_length=20)),
                ('appointment_type', models.CharField(choices=[('single', 'Single Appointment'), ('subscription', 'Subscription Appointment'), ('order_item', 'Order Item Appointment')], default='single', help_text='Appointment type: single, subscription, or order_item', max_length=20)),
                ('calendar_event_id', models.JSONField(blank=True, default=dict, help_text='Calendar event IDs for each provider (JSON): {"google": "event_id", "outlook": "event_id", "apple": "event_id"}')),
                ('calendar_synced_to', models.JSONField(blank=True, default=list, help_text='List of calendars this appointment is synced to (JSON array): ["google", "outlook", "apple"]')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff/admin', null=True)),
                ('location_notes', models.TextField(blank=True, help_text='Location-specific notes (gate codes, parking, etc.)', null=True)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'db_table': 'appointments_appointment',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_persons', models.IntegerField(default=1, help_text='Number of persons', validators=[django.core.validators.MinValueValidator(1)])),
                ('extras', models.JSONField(blank=True, default=list, help_text='Additional services/extras (JSON array)')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom fields filled during booking (JSON)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this appointment', max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount paid', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('cancellation_token', models.CharField(blank=True, help_text='Unique token for cancellation/rescheduling (for guest orders)', max_length=100, null=True, unique=True)),
                ('cancellation_policy_hours', models.IntegerField(default=24, help_text='Cancellation policy hours (default: 24 hours before appointment)')),
                ('cancellation_deadline', models.DateTimeField(blank=True, help_text='Deadline for cancellation (24 hours before appointment start time)', null=True)),
                ('can_cancel', models.BooleanField(default=True, help_text='Can cancel this appointment (based on 24h policy)')),
                ('can_reschedule', models.BooleanField(default=True, help_text='Can reschedule this appointment (based on 24h policy)')),
            ],
            options={
                'verbose_name': 'customer appointment',
                'verbose_name_plural': 'customer appointments',
                'db_table': 'appointments_customerappointment',
                'ordering': ['appointment__start_time'],
            },
        ),
    ]
