# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this appointment belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Service being performed', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(help_text='Staff member assigned to this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription this appointment belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='customerappointment',
            name='appointment',
            field=models.OneToOneField(help_text='Appointment', on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='customerappointment',
            name='customer',
            field=models.ForeignKey(help_text='Customer who booked this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'start_time'], name='appointment_staff_i_7434a5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_time'], name='appointment_status_74937b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_type'], name='appointment_appoint_3d8254_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['subscription'], name='appointment_subscri_de1689_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['order'], name='appointment_order_i_facef5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerappointment',
            index=models.Index(fields=['customer'], name='appointment_custome_413569_idx'),
        ),
        migrations.AddIndex(
            model_name='customerappointment',
            index=models.Index(fields=['cancellation_token'], name='appointment_cancell_ccec98_idx'),
        ),
        migrations.AddIndex(
            model_name='customerappointment',
            index=models.Index(fields=['can_cancel', 'can_reschedule'], name='appointment_can_can_14af65_idx'),
        ),
    ]
