# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_add_completion_photos'),
        ('customers', '0002_address_address_valid_type_and_more'),
        ('orders', '0002_changerequest'),
        ('services', '0003_category_category_name_not_empty_and_more'),
        ('staff', '0004_staff_staff_name_not_empty_and_more'),
        ('subscriptions', '0002_subscriptionappointment_can_reschedule_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show'])), name='appointment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('appointment_type__in', ['single', 'subscription', 'order_item'])), name='appointment_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='customerappointment',
            constraint=models.CheckConstraint(check=models.Q(('number_of_persons__gte', 1)), name='customerappointment_valid_persons'),
        ),
        migrations.AddConstraint(
            model_name='customerappointment',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='customerappointment_valid_total_price'),
        ),
        migrations.AddConstraint(
            model_name='customerappointment',
            constraint=models.CheckConstraint(check=models.Q(('deposit_paid__gte', 0)), name='customerappointment_valid_deposit'),
        ),
        migrations.AddConstraint(
            model_name='customerappointment',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['pending', 'partial', 'paid', 'refunded'])), name='customerappointment_valid_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='customerappointment',
            constraint=models.CheckConstraint(check=models.Q(('cancellation_policy_hours__gt', 0)), name='customerappointment_valid_policy_hours'),
        ),
    ]
