# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly category name (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/')),
                ('position', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Category is active and visible')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'services_category',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Service name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly service name (auto-generated)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('duration', models.IntegerField(help_text='Service duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price for this service', max_digits=10)),
                ('currency', models.CharField(default='GBP', help_text='Currency code (GBP, USD, etc.)', max_length=3)),
                ('image', models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/')),
                ('color', models.CharField(default='#3B82F6', help_text='Color code for calendar/service display (hex)', max_length=7)),
                ('capacity', models.IntegerField(default=1, help_text='Number of customers that can book this service simultaneously')),
                ('padding_time', models.IntegerField(default=0, help_text='Padding time in minutes before next appointment')),
                ('position', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Service is active and available for booking')),
                ('category', models.ForeignKey(help_text='Service category', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services_service',
                'ordering': ['position', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='services_se_categor_b50c86_idx'), models.Index(fields=['slug'], name='services_se_slug_4657d0_idx')],
            },
        ),
    ]
