# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_extras_approval'),
        ('staff', '0003_staffarea_service'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), name='category_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='category_valid_position'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), name='service_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', 0)), name='service_valid_duration'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='service_valid_price'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='service_valid_capacity'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('padding_time__gte', 0)), name='service_valid_padding_time'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('approval_status__in', ['approved', 'pending_approval'])), name='service_valid_approval_status'),
        ),
    ]
