# Generated by Django 5.0.1 on 2025-12-01 19:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=9999, help_text='For ordering')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('info', models.TextField(blank=True, help_text='Staff bio/information')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('calendar_provider', models.CharField(choices=[('none', 'None'), ('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('apple', 'Apple Calendar')], default='none', max_length=20)),
                ('calendar_id', models.CharField(blank=True, help_text='Calendar ID from the provider', max_length=255)),
                ('calendar_data', models.JSONField(blank=True, default=dict, help_text='Provider-specific calendar configuration')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['position', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('repeat_event', models.BooleanField(default=False, help_text='Repeat this holiday yearly')),
                ('staff', models.ForeignKey(blank=True, help_text='Leave null for company-wide holidays', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='staff.staff')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StaffScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('breaks', models.JSONField(blank=True, default=list, help_text="List of break periods: [{'start': 'HH:MM', 'end': 'HH:MM'}]")),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='staff.staff')),
            ],
            options={
                'ordering': ['day_index', 'start_time'],
                'unique_together': {('staff', 'day_index')},
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for this staff-service combination', max_digits=10, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Custom capacity for this staff-service combination', null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Deposit percentage or fixed amount', max_digits=5)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff.staff')),
            ],
            options={
                'ordering': ['staff', 'service'],
                'unique_together': {('staff', 'service')},
            },
        ),
    ]
