# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Staff member full name', max_length=200)),
                ('email', models.EmailField(help_text='Staff email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Staff phone number (UK format)', max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Staff photo', null=True, upload_to='staff/')),
                ('bio', models.TextField(blank=True, help_text='Staff biography/description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Staff member is active and available for booking')),
                ('user', models.ForeignKey(blank=True, help_text='Staff user account (optional - for portal access)', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff member',
                'verbose_name_plural': 'staff members',
                'db_table': 'staff_staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for this staff member (overrides service base price)', max_digits=10, null=True)),
                ('duration_override', models.IntegerField(blank=True, help_text='Custom duration in minutes (overrides service base duration)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='This staff-service assignment is active')),
                ('service', models.ForeignKey(help_text='Service', on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.service')),
                ('staff', models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff.staff')),
            ],
            options={
                'verbose_name': 'staff service',
                'verbose_name_plural': 'staff services',
                'db_table': 'staff_staffservice',
                'ordering': ['staff', 'service'],
                'unique_together': {('staff', 'service')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services this staff member can perform', related_name='staff_members', through='staff.StaffService', to='services.service'),
        ),
        migrations.CreateModel(
            name='StaffArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postcode', models.CharField(help_text='Center postcode (e.g., SW1A 1AA)', max_length=20)),
                ('radius_km', models.DecimalField(decimal_places=2, help_text='Service radius in kilometers from center postcode', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='This service area is active')),
                ('staff', models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='staff.staff')),
            ],
            options={
                'verbose_name': 'staff service area',
                'verbose_name_plural': 'staff service areas',
                'db_table': 'staff_staffarea',
                'ordering': ['staff', 'postcode'],
                'indexes': [models.Index(fields=['postcode', 'is_active'], name='staff_staff_postcod_17cd79_idx'), models.Index(fields=['staff', 'is_active'], name='staff_staff_staff_i_a895cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Work start time')),
                ('end_time', models.TimeField(help_text='Work end time')),
                ('breaks', models.JSONField(blank=True, default=list, help_text='Break periods (JSON array): [{"start": "12:00", "end": "13:00"}]')),
                ('is_active', models.BooleanField(default=True, help_text='This schedule entry is active')),
                ('staff', models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.staff')),
            ],
            options={
                'verbose_name': 'staff schedule',
                'verbose_name_plural': 'staff schedules',
                'db_table': 'staff_staffschedule',
                'ordering': ['staff', 'day_of_week'],
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active', 'email'], name='staff_staff_is_acti_5c62d9_idx'),
        ),
    ]
