# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_category_name_not_empty_and_more'),
        ('staff', '0003_staffarea_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), name='staff_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='staff_email_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='staffarea',
            constraint=models.CheckConstraint(check=models.Q(('radius_miles__gt', 0)), name='staffarea_valid_radius'),
        ),
        migrations.AddConstraint(
            model_name='staffarea',
            constraint=models.CheckConstraint(check=models.Q(('postcode__isnull', False), models.Q(('postcode', ''), _negated=True)), name='staffarea_postcode_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.CheckConstraint(check=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='staffschedule_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='staffschedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.CheckConstraint(check=models.Q(('price_override__isnull', True), ('price_override__gt', 0), _connector='OR'), name='staffservice_valid_price_override'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.CheckConstraint(check=models.Q(('duration_override__isnull', True), ('duration_override__gt', 0), _connector='OR'), name='staffservice_valid_duration_override'),
        ),
    ]
