# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest orders (required if customer is NULL)', max_length=254, null=True)),
                ('guest_name', models.CharField(blank=True, help_text='Name for guest orders', max_length=200, null=True)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone for guest orders', max_length=20, null=True)),
                ('order_number', models.CharField(db_index=True, help_text='Unique order number (e.g., ORD-20240115-ABC123)', max_length=50, unique=True)),
                ('tracking_token', models.CharField(db_index=True, help_text='Unique tracking token for guest order access via email link', max_length=100, unique=True)),
                ('is_guest_order', models.BooleanField(default=False, help_text='Flag for guest orders (no account required)')),
                ('account_linked_at', models.DateTimeField(blank=True, help_text='When guest order was linked to customer account', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total order price', max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount paid', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Preferred service date')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Preferred service time (optional)', null=True)),
                ('cancellation_policy_hours', models.IntegerField(default=24, help_text='Cancellation policy hours (default: 24 hours before scheduled date/time)')),
                ('can_cancel', models.BooleanField(default=True, help_text='Can cancel this order (based on 24h policy)')),
                ('can_reschedule', models.BooleanField(default=True, help_text='Can reschedule this order (based on 24h policy)')),
                ('cancellation_deadline', models.DateTimeField(blank=True, help_text='Deadline for cancellation/rescheduling (24 hours before scheduled date/time)', null=True)),
                ('address_line1', models.CharField(help_text='Service address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Service address line 2', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('postcode', models.CharField(help_text='Postcode (UK format)', max_length=20)),
                ('country', models.CharField(default='United Kingdom', help_text='Country', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or special instructions', null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer (NULL for guest orders, linked after login/registration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of this service', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity * unit_price)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Order item status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Item-specific notes', null=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Appointment created for this order item (created when order is confirmed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='appointments.appointment')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('service', models.ForeignKey(help_text='Service for this order item', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.service')),
                ('staff', models.ForeignKey(blank=True, help_text='Assigned staff member (optional - can be assigned later)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='staff.staff')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'orders_orderitem',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_token'], name='orders_orde_trackin_fb511c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_guest_order', 'guest_email'], name='orders_orde_is_gues_8217f9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'scheduled_date'], name='orders_orde_status_03ad6e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['postcode'], name='orders_orde_postcod_372e67_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_3360fc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['service'], name='orders_orde_service_4e362f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['staff'], name='orders_orde_staff_i_6686ea_idx'),
        ),
    ]
