# Generated by Django 5.2.10 on 2026-01-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_date', models.DateField(help_text='Requested new date')),
                ('requested_time', models.TimeField(blank=True, help_text='Requested new time (optional)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for change request', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Change request status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this change request was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin review notes', null=True)),
                ('order', models.ForeignKey(help_text='Order for this change request', on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this change request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'change request',
                'verbose_name_plural': 'change requests',
                'db_table': 'orders_changerequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_chan_order_i_06da21_idx')],
            },
        ),
    ]
