# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_valid_status_and_more'),
        ('customers', '0002_address_address_valid_type_and_more'),
        ('orders', '0002_changerequest'),
        ('services', '0003_category_category_name_not_empty_and_more'),
        ('staff', '0004_staff_staff_name_not_empty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='changerequest_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.CheckConstraint(check=models.Q(('requested_date__isnull', False)), name='changerequest_has_date'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'confirmed', 'in_progress', 'completed', 'cancelled'])), name='order_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['pending', 'partial', 'paid', 'refunded'])), name='order_valid_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='order_valid_total_price'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('deposit_paid__gte', 0)), name='order_valid_deposit'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('cancellation_policy_hours__gt', 0)), name='order_valid_policy_hours'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('order_number__isnull', False), models.Q(('order_number', ''), _negated=True)), name='order_number_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('tracking_token__isnull', False), models.Q(('tracking_token', ''), _negated=True)), name='order_tracking_token_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('customer__isnull', False), models.Q(('guest_email__isnull', False), models.Q(('guest_email', ''), _negated=True)), _connector='OR'), name='order_has_customer_or_guest_email'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='orderitem_valid_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gt', 0)), name='orderitem_valid_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='orderitem_valid_total_price'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'confirmed', 'in_progress', 'completed', 'cancelled'])), name='orderitem_valid_status'),
        ),
    ]
