# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest subscriptions (required if customer is NULL)', max_length=254, null=True)),
                ('guest_name', models.CharField(blank=True, help_text='Name for guest subscriptions', max_length=200, null=True)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone for guest subscriptions', max_length=20, null=True)),
                ('subscription_number', models.CharField(db_index=True, help_text='Unique subscription number (e.g., SUB-20240115-ABC123)', max_length=50, unique=True)),
                ('tracking_token', models.CharField(db_index=True, help_text='Unique tracking token for guest subscription access via email link', max_length=100, unique=True)),
                ('is_guest_subscription', models.BooleanField(default=False, help_text='Flag for guest subscriptions (no account required)')),
                ('account_linked_at', models.DateTimeField(blank=True, help_text='When guest subscription was linked to customer account', null=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], help_text='Subscription frequency: weekly, biweekly, or monthly', max_length=20)),
                ('duration_months', models.IntegerField(help_text='Subscription duration in months (1, 2, 3, 6, or 12)', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(help_text='Subscription start date')),
                ('end_date', models.DateField(help_text='Subscription end date (calculated)')),
                ('next_appointment_date', models.DateField(blank=True, help_text='Next scheduled appointment date', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', help_text='Subscription status', max_length=20)),
                ('total_appointments', models.IntegerField(default=0, help_text='Total number of appointments in this subscription (calculated)')),
                ('completed_appointments', models.IntegerField(default=0, help_text='Number of completed appointments')),
                ('price_per_appointment', models.DecimalField(decimal_places=2, help_text='Price per appointment', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total subscription price', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('cancellation_policy_hours', models.IntegerField(default=24, help_text='Cancellation policy hours (default: 24 hours before appointment)')),
                ('address_line1', models.CharField(blank=True, help_text='Guest address line 1', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, help_text='Guest address line 2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='Guest city', max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Guest postcode', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='United Kingdom', help_text='Guest country', max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer (NULL for guest subscriptions, linked after login/registration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='customers.customer')),
                ('service', models.ForeignKey(help_text='Service for subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.service')),
                ('staff', models.ForeignKey(blank=True, help_text='Preferred staff member (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='staff.staff')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.IntegerField(help_text='Sequence number in subscription (1, 2, 3, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_date', models.DateField(help_text='Scheduled date for this appointment')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='scheduled', help_text='Subscription appointment status', max_length=20)),
                ('can_cancel', models.BooleanField(default=True, help_text='Can cancel this subscription appointment (based on 24h policy)')),
                ('cancellation_deadline', models.DateTimeField(blank=True, help_text='Deadline for cancellation (24 hours before appointment start time)', null=True)),
                ('appointment', models.ForeignKey(help_text='Appointment', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_appointments', to='appointments.appointment')),
                ('subscription', models.ForeignKey(help_text='Parent subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_appointments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'subscription appointment',
                'verbose_name_plural': 'subscription appointments',
                'db_table': 'subscriptions_subscriptionappointment',
                'ordering': ['subscription', 'sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_number'], name='subscriptio_subscri_c33376_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tracking_token'], name='subscriptio_trackin_ad3212_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='subscriptio_custome_cea13a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_guest_subscription', 'guest_email'], name='subscriptio_is_gues_04a947_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'next_appointment_date'], name='subscriptio_status_a8dc67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionappointment',
            unique_together={('subscription', 'appointment')},
        ),
    ]
