# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_valid_status_and_more'),
        ('customers', '0002_address_address_valid_type_and_more'),
        ('services', '0003_category_category_name_not_empty_and_more'),
        ('staff', '0004_staff_staff_name_not_empty_and_more'),
        ('subscriptions', '0002_subscriptionappointment_can_reschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('frequency__in', ['weekly', 'biweekly', 'monthly'])), name='subscription_valid_frequency'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'paused', 'cancelled', 'completed'])), name='subscription_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['pending', 'partial', 'paid', 'refunded'])), name='subscription_valid_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('duration_months__gte', 1)), name='subscription_valid_duration'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('total_appointments__gte', 0)), name='subscription_valid_total_appointments'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('completed_appointments__gte', 0)), name='subscription_valid_completed_appointments'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('completed_appointments__lte', models.F('total_appointments'))), name='subscription_completed_not_exceeds_total'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('price_per_appointment__gt', 0)), name='subscription_valid_price_per_appointment'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='subscription_valid_total_price'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='subscription_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscription_number__isnull', False), models.Q(('subscription_number', ''), _negated=True)), name='subscription_number_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('tracking_token__isnull', False), models.Q(('tracking_token', ''), _negated=True)), name='subscription_tracking_token_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('customer__isnull', False), models.Q(('guest_email__isnull', False), models.Q(('guest_email', ''), _negated=True)), _connector='OR'), name='subscription_has_customer_or_guest_email'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionappointment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['scheduled', 'completed', 'cancelled', 'skipped'])), name='subscriptionappointment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionappointment',
            constraint=models.CheckConstraint(check=models.Q(('sequence_number__gte', 1)), name='subscriptionappointment_valid_sequence'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionappointmentchangerequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='subscriptionappointmentchangerequest_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionappointmentchangerequest',
            constraint=models.CheckConstraint(check=models.Q(('requested_date__isnull', False)), name='subscriptionappointmentchangerequest_has_date'),
        ),
    ]
