# Generated by Django 5.2.10 on 2026-01-10 20:17

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer', help_text='User role: admin, manager, staff, or customer', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('username', models.CharField(blank=True, help_text='Optional username. Email is used as primary identifier.', max_length=150, null=True, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Permission configuration (JSON): can_manage_customers, can_manage_staff, etc.')),
                ('can_manage_all', models.BooleanField(default=False, help_text='Can manage all staff and customers (full manager access)')),
                ('can_manage_customers', models.BooleanField(default=False, help_text='Can manage customers (within assigned scope)')),
                ('can_manage_staff', models.BooleanField(default=False, help_text='Can manage staff (within assigned scope)')),
                ('can_manage_appointments', models.BooleanField(default=True, help_text='Can manage appointments (within assigned scope)')),
                ('can_view_reports', models.BooleanField(default=True, help_text='Can view reports (within assigned scope)')),
                ('managed_locations', models.JSONField(blank=True, default=list, help_text='List of location IDs this manager can manage (JSON array)')),
                ('is_active', models.BooleanField(default=True, help_text='Manager account is active')),
                # ManyToMany fields will be added in a later migration after customers and staff are created
                ('user', models.OneToOneField(help_text='Manager user (must have role=manager)', limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
                'db_table': 'accounts_manager',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number (UK format)', max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='Europe/London', help_text='User timezone (e.g., Europe/London)', max_length=50)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences (JSON)')),
                ('calendar_sync_enabled', models.BooleanField(default=False, help_text='Enable calendar synchronization')),
                ('calendar_provider', models.CharField(choices=[('none', 'None'), ('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('apple', 'Apple Calendar')], default='none', help_text='Calendar provider: google, outlook, apple, or none', max_length=20)),
                ('calendar_access_token', models.TextField(blank=True, help_text='Encrypted calendar access token', null=True)),
                ('calendar_refresh_token', models.TextField(blank=True, help_text='Encrypted calendar refresh token', null=True)),
                ('calendar_calendar_id', models.CharField(blank=True, help_text='Calendar ID from provider (e.g., Google Calendar ID)', max_length=255, null=True)),
                ('calendar_sync_settings', models.JSONField(blank=True, default=dict, help_text='Calendar sync preferences (JSON): auto_sync, sync_direction, etc.')),
                ('user', models.OneToOneField(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'accounts_profile',
            },
        ),
    ]
