# Generated by Django 5.2.10 on 2026-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='managed_customers',
            field=models.ManyToManyField(blank=True, help_text='Customers this manager can manage', related_name='managing_managers', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='manager',
            name='managed_staff',
            field=models.ManyToManyField(blank=True, help_text='Staff members this manager can manage', related_name='managing_managers', to='staff.staff'),
        ),
    ]
