# Generated by Django 5.2.10 on 2026-01-11 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manager_managed_customers_manager_managed_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Manager is active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_access_token',
            field=models.TextField(blank=True, help_text='Calendar access token (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_calendar_id',
            field=models.CharField(blank=True, help_text='Primary calendar ID for sync', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_provider',
            field=models.CharField(choices=[('none', 'None'), ('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('apple', 'Apple Calendar')], default='none', help_text='Calendar provider (Google, Outlook, Apple, None)', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_refresh_token',
            field=models.TextField(blank=True, help_text='Calendar refresh token (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_sync_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Calendar sync settings (two-way sync, sync direction, etc.)'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address to invite', max_length=254)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin')], help_text='Role for the invited user', max_length=20)),
                ('token', models.CharField(db_index=True, help_text='Unique invitation token', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiration date')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the invitation was used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this invitation is active')),
                ('invited_by', models.ForeignKey(help_text='User who created this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'db_table': 'accounts_invitation',
                'indexes': [models.Index(fields=['token', 'is_active'], name='accounts_in_token_eb512a_idx'), models.Index(fields=['email', 'role'], name='accounts_in_email_af4583_idx')],
            },
        ),
    ]
