# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_manager_is_active_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['staff', 'manager', 'admin'])), name='invitation_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('created_at'))), name='invitation_expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='invitation_email_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['admin', 'manager', 'staff', 'customer'])), name='user_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='user_email_not_empty'),
        ),
    ]
