# Generated by Django 5.0.1 on 2025-12-01 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repeat_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('repeat_interval', models.IntegerField(default=1, help_text='Repeat every X days/weeks/months', validators=[django.core.validators.MinValueValidator(1)])),
                ('until_date', models.DateField(blank=True, null=True)),
                ('occurrences', models.IntegerField(blank=True, help_text='Number of occurrences (alternative to until_date)', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('calendar_event_id', models.CharField(blank=True, help_text='Event ID from calendar provider (Google/Outlook/Apple)', max_length=255)),
                ('calendar_provider', models.CharField(choices=[('none', 'None'), ('google', 'Google'), ('outlook', 'Outlook'), ('apple', 'Apple')], default='none', max_length=20)),
                ('internal_note', models.TextField(blank=True, help_text='Internal notes (not visible to customers)')),
                ('extras_duration', models.IntegerField(default=0, help_text='Additional duration from extras in minutes')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staff.staff')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.series')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('number_of_persons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('extras', models.JSONField(blank=True, default=list, help_text='Selected service extras')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Custom field values')),
                ('token', models.CharField(blank=True, help_text='Unique token for cancellation/approval links', max_length=64, unique=True)),
                ('time_zone_offset', models.IntegerField(default=0, help_text='Client timezone offset in minutes')),
                ('compound_token', models.CharField(blank=True, help_text='Token for multi-appointment bookings', max_length=64)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='appointments.appointment')),
                ('compound_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compound_appointments', to='services.service')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='customers.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_appointments', to='payments.payment')),
            ],
            options={
                'ordering': ['appointment__start_date'],
                'indexes': [models.Index(fields=['customer', 'status'], name='appointment_custome_93e9de_idx'), models.Index(fields=['token'], name='appointment_token_21ab7c_idx'), models.Index(fields=['compound_token'], name='appointment_compoun_d28224_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'start_date'], name='appointment_staff_i_07d2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_date', 'end_date'], name='appointment_start_d_d9ee83_idx'),
        ),
    ]
