# Generated by Django 5.0.1 on 2025-12-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=9999, help_text='For ordering')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('date', 'Date'), ('file', 'File Upload'), ('captcha', 'Captcha')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('items', models.JSONField(blank=True, default=list, help_text='Options for select/checkbox/radio fields')),
                ('services', models.ManyToManyField(blank=True, help_text='Services this field applies to (empty = all services)', related_name='custom_fields', to='services.service')),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
    ]
