# Generated by Django 5.2.10 on 2026-01-11 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Customer full name', max_length=200)),
                ('email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Customer phone number (UK format)', max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, help_text='Address line 1', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Postcode (UK format)', max_length=20, null=True)),
                ('country', models.CharField(default='United Kingdom', help_text='Country', max_length=100)),
                ('address_validated', models.BooleanField(default=False, help_text='Address has been validated via Google Places API')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this customer', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Customer tags (JSON array): ["vip", "repeat", etc.]')),
                ('user', models.ForeignKey(blank=True, help_text='Customer user account (optional - can be NULL for guest customers)', limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customers_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('billing', 'Billing Address'), ('service', 'Service Address'), ('other', 'Other')], default='service', help_text='Address type: billing, service, or other', max_length=20)),
                ('address_line1', models.CharField(help_text='Address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('postcode', models.CharField(help_text='Postcode (UK format)', max_length=20)),
                ('country', models.CharField(default='United Kingdom', help_text='Country', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Default address for this customer')),
                ('address_validated', models.BooleanField(default=False, help_text='Address has been validated via Google Places API')),
                ('customer', models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'customers_address',
                'ordering': ['customer', '-is_default', 'type'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['postcode'], name='customers_c_postcod_729241_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='customers_c_user_id_c1d57c_idx'),
        ),
    ]
