# Generated by Django 5.0.1 on 2026-02-15 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['billing', 'service', 'other'])), name='address_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('address_line1__isnull', False), models.Q(('address_line1', ''), _negated=True)), name='address_line1_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('city__isnull', False), models.Q(('city', ''), _negated=True)), name='address_city_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('postcode__isnull', False), models.Q(('postcode', ''), _negated=True)), name='address_postcode_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), name='customer_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='customer_email_not_empty'),
        ),
    ]
