# Generated by Django 5.2.10 on 2026-01-19 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Coupon code (e.g., SAVE20, WELCOME10)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Coupon name/description', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], help_text='Discount type: percentage or fixed amount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage: 0-100, fixed: amount in GBP)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this coupon can be used (NULL = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_uses_per_customer', models.IntegerField(blank=True, default=1, help_text='Maximum number of times a single customer can use this coupon (NULL = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('used_count', models.IntegerField(default=0, help_text='Number of times this coupon has been used', validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from date/time')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Coupon valid until date/time (NULL = no expiry)', null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', help_text='Coupon status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Coupon description/terms', null=True)),
                ('applicable_services', models.ManyToManyField(blank=True, help_text='Services this coupon applies to (empty = all services)', related_name='coupons', to='services.service')),
                ('excluded_services', models.ManyToManyField(blank=True, help_text='Services this coupon does NOT apply to', related_name='excluded_coupons', to='services.service')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'db_table': 'coupons_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Guest email if customer is NULL', max_length=254, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount amount applied', max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=2, help_text='Order amount before discount', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Order amount after discount', max_digits=10)),
                ('appointment', models.ForeignKey(blank=True, help_text='Appointment where coupon was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='appointments.appointment')),
                ('coupon', models.ForeignKey(help_text='Coupon used', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer who used the coupon (NULL for guest usage)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Order where coupon was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order')),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription where coupon was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'coupon usage',
                'verbose_name_plural': 'coupon usages',
                'db_table': 'coupons_couponusage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'valid_from', 'valid_until'], name='coupons_cou_status_a34176_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'customer'], name='coupons_cou_coupon__46300b_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['order'], name='coupons_cou_order_i_961167_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['subscription'], name='coupons_cou_subscri_aaaa86_idx'),
        ),
    ]
