# Generated by Django 5.0.1 on 2026-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_valid_status_and_more'),
        ('coupons', '0001_initial'),
        ('customers', '0002_address_address_valid_type_and_more'),
        ('orders', '0003_changerequest_changerequest_valid_status_and_more'),
        ('services', '0003_category_category_name_not_empty_and_more'),
        ('subscriptions', '0003_subscription_subscription_valid_frequency_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_type__in', ['percentage', 'fixed'])), name='coupon_valid_discount_type'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'inactive', 'expired'])), name='coupon_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_value__gt', 0)), name='coupon_valid_discount_value'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_type', 'fixed'), ('discount_value__lte', 100), _connector='OR'), name='coupon_percentage_max_100'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('used_count__gte', 0)), name='coupon_valid_used_count'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('max_uses__isnull', True), ('max_uses__gte', 1), _connector='OR'), name='coupon_valid_max_uses'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('max_uses_per_customer__isnull', True), ('max_uses_per_customer__gte', 1), _connector='OR'), name='coupon_valid_max_uses_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('minimum_order_amount__gte', 0)), name='coupon_valid_minimum_order_amount'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), name='coupon_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='couponusage_valid_discount_amount'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(check=models.Q(('order_amount__gt', 0)), name='couponusage_valid_order_amount'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(check=models.Q(('final_amount__gte', 0)), name='couponusage_valid_final_amount'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(check=models.Q(('final_amount__lte', models.F('order_amount'))), name='couponusage_final_not_exceeds_order'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(check=models.Q(('customer__isnull', False), models.Q(('guest_email__isnull', False), models.Q(('guest_email', ''), _negated=True)), _connector='OR'), name='couponusage_has_customer_or_guest_email'),
        ),
    ]
