# Generated by Django 5.0.1 on 2025-12-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=9999, help_text='For ordering')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=9999, help_text='For ordering')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=900, help_text='Duration in minutes (default: 15 minutes)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('color', models.CharField(default='#DDDDDD', help_text='Hex color code for calendar display', max_length=7)),
                ('capacity', models.IntegerField(default=1, help_text='Maximum number of persons per appointment')),
                ('padding_left', models.IntegerField(default=0, help_text='Buffer time before service in minutes')),
                ('padding_right', models.IntegerField(default=0, help_text='Buffer time after service in minutes')),
                ('service_type', models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound')], default='simple', max_length=20)),
                ('sub_services', models.JSONField(blank=True, default=list, help_text='List of sub-service IDs for compound services')),
                ('start_time', models.TimeField(blank=True, help_text='Start time for all-day services', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for all-day services', null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.category')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
    ]
