# Generated by Django 5.0.1 on 2025-12-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('event_type', models.CharField(choices=[('new', 'New Appointment'), ('approved', 'Appointment Approved'), ('cancelled', 'Appointment Cancelled'), ('rejected', 'Appointment Rejected'), ('reminder', 'Reminder'), ('follow_up', 'Follow-up')], max_length=20)),
                ('send_to', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(help_text='Message template with placeholders')),
                ('reminder_hours_before', models.IntegerField(blank=True, help_text='Hours before appointment to send reminder (for reminder type)', null=True)),
            ],
            options={
                'ordering': ['event_type', 'type', 'send_to'],
                'unique_together': {('type', 'event_type', 'send_to')},
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipient', models.CharField(help_text='Email or phone number', max_length=255)),
                ('customer_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='appointments.customerappointment')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'sent_at'], name='notificatio_status_ac52b4_idx')],
            },
        ),
    ]
